debug: false
management.endpoints.web.exposure.include: "*" # actuator의 endpoint 중 감춰진 걸 보여줌
logging:
  level:
    com.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306:board
    username: tae
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # for test data
    hibernate.ddl-auto: create
    show-sql: true
#    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always # test data init
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated

---

spring:
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
